Models/UserRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IdentityCore.Models
{
    public class UserRoleViewModel
    {
        public string RoleName { get; set; }
        public bool Selected { get; set; }
    }
    public class ManageUserRolesViewModel
    {
        public string UserId { get; set; }
        public IList<UserRoleViewModel> UserRoles { get; set; }
    }
}

Controllers/UserRoleController.cs
using IdentityCore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IdentityCore.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserRoleController : Controller
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public UserRoleController(SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index(string userId)
        {
            var viewModel = new List<UserRoleViewModel>();
            var user = await _userManager.FindByIdAsync(userId);
            foreach (var item in _roleManager.Roles)
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    RoleName = item.Name
                };
                if (await _userManager.IsInRoleAsync(user, item.Name))
                {
                    userRoleViewModel.Selected = true;
                }
                else
                {
                    userRoleViewModel.Selected = false;
                }
                viewModel.Add(userRoleViewModel);
            }
            var model = new ManageUserRolesViewModel()
            {
                UserId = userId,
                UserRoles = viewModel
            };
            return View(model);
        }
        public async Task<IActionResult> Update(string id, ManageUserRolesViewModel model)
        {
            var user = await _userManager.FindByIdAsync(id);
            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);
            result = await _userManager.AddToRolesAsync(user, model.UserRoles.Where(i=>i.Selected).Select(i=>i.RoleName));
            var currentUser = await _userManager.GetUserAsync(User);
            await _signInManager.RefreshSignInAsync(currentUser);
            await Seeds.DefaultUsers.SeedAdminAsync(_userManager, _roleManager);

            return RedirectToAction("Index", new { UserId = id });
        }
    }
}

Views/UserRole/Index.cshtml
@model IdentityCore.Models.ManageUserRolesViewModel
@{ 
    ViewData["Title"] = "Manage Role for "+Model.UserId;
}

<h3>@ViewData["Title"]</h3>

<div class="container">
    <div class="row">
        <div class="card">
            <div id="viewAll" class="card-body table-responsive">
                <form asp-controller="UserRole" asp-action="Update" asp-route-id="@Model.UserId" method="post" class="d-inline"> 
                    <input asp-for="@Model.UserId" type="hidden"/>
                    <table class="table table-striped" id="userRolesTable">
                        <thead>
                            <tr>
                                <th>Role</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < Model.UserRoles.Count(); i++)
                            {
                                <tr>
                                    <td>
                                        <input asp-for="@Model.UserRoles[i].RoleName" type="hidden" />
                                        @Model.UserRoles[i].RoleName
                                    </td>
                                    <td>
                                        <div class="form-check m-1">
                                            <input asp-for="@Model.UserRoles[i].Selected" class="form-check-input" />
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <div class="col-sm-12" style="padding:20px 20px 0px 0px">
                        <button type="submit"  id="save" class="btn bg-primary"><i class="fa fa-check"></i>Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>