Controllers/PermissionController.cs
using IdentityCore.Constants;
using IdentityCore.Helpers;
using IdentityCore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IdentityCore.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PermissionController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        public PermissionController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index(string roleId)
        {
            var model = new PermissionViewModel();
            var allPermissions = new List<RoleClaimsViewModel>();
            allPermissions.GetPermissions(typeof(Permissions.Products), roleId);
            var role = await _roleManager.FindByIdAsync(roleId);
            model.RoleId = roleId;
            var claims = await _roleManager.GetClaimsAsync(role);
            var allClaimValues = allPermissions.Select(i => i.Value).ToList();
            var roleClaimValues = claims.Select(i => i.Value).ToList();
            var authorizedClaims = allClaimValues.Intersect(roleClaimValues).ToList();
            foreach (var item in allPermissions)
            {
                if (authorizedClaims.Any(i => i == item.Value))
                {
                    item.Selected = true;
                }
            }
            model.RoleClaims = allPermissions;
            return View(model);
        }
        public async Task<IActionResult> Update(PermissionViewModel model)
        {
            var role = await _roleManager.FindByIdAsync(model.RoleId);
            var claims = await _roleManager.GetClaimsAsync(role);
            foreach (var item in claims)
            {
                await _roleManager.RemoveClaimAsync(role, item);
            }
            var selectedClaims = model.RoleClaims.Where(i => i.Selected).ToList();
            foreach (var item in selectedClaims)
            {
                await _roleManager.AddPermissionClaim(role, item.Value);
            }
            return RedirectToAction("Index", new { roleId = model.RoleId });
        }
    }
}

Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IdentityCore.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }
        public async Task<IActionResult> CreateRole(string roleName)
        {
            if (roleName!=null)
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Role/Index.cshtml
@using Microsoft.AspNetCore.Identity
@model IEnumerable<IdentityRole>
@{
    ViewData["Title"] = "Role List";
}

<h3>@ViewData["Title"]</h3>

<div class="container">
    <div class="row">
        <div class="col-md-10">
            <form method="post" asp-action="CreateRole" asp-controller="Role">
                <div class="input-group">
                    <input name="roleName" class="form-control w-25" />
                    <span class="input-group-btn">
                        <button class="btn btn-info">Add to Role</button>
                    </span>
                </div>
            </form>
            <hr />
            <table class="table table-hover" id="roleTable">
                <thead>
                    <tr>
                        <th>Role</th>
                        <th>Id</th>
                        <th style="width:10%">Role</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @item.Name
                            </td>
                            <td>
                                @item.Id
                            </td>
                            <td class="text-right">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action</button>
                                    <div class="dropdown-menu shadow animated--grow-in">
                                        <a class="dropdown-item"><i class="fas fa-pencil-alt"></i>Edit</a>
                                        <form class="d-inline">
                                            <a class="dropdown-item">
                                                <i class="fas fa-trash-alt"></i>
                                                Delete
                                            </a>
                                        </form>
                                        @if (item.Name != "Admin")
                                        {
                                            <a style="margin-right:16px" asp-controller="Permission" asp-action="Index" asp-route-roleId="@item.Id" class="dropdown-item"><i class="fas fa-wrench"></i>Manage Permissions</a>
                                        }
                                    </div>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>